from . import account_deductee_type
from . import tds_section
from . import hsn_code
from . import account_tax
from . import account_account
from . import res_partner
from . import product_template
from . import product_product
from . import account_payment_term
from . import purchase_order
from . import sale_order
from . import advance_payment_orders
from . import account_partial_line
from . import account_payment
from . import account_move
from . import account_move_line
from . import account_partner_ledger
