{
    'name': 'GTS Stock',
    'version': '16.0',
    'summary': 'GTS Stock',
    'author': 'Geotechnosoft',
    'maintainer': 'Geotechnosoft',
    'company': 'Geotechnosoft',
    'website': 'https://planet-odoo.com/',
    'depends': ['base', 'stock'],
    'category': 'Accounting',
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'views/stock_picking_view.xml',
        'wizard/select_warehouse_wizard_view.xml',
    ],
    'installable': True,
    'images': [],
    'qweb': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
}
