from . import product_template
from . import product_product
from . import account_move
from . import sale_order
from . import purchase_order
from . import stock_picking
from . import approval_request
from . import res_partner
from . import import_attributes
from . import alias_name_master
from . import inherit_stock_warehouse
from . import location_report_xls
from . import update_partner
from . import hr_payslip_run
