from odoo import models, fields, api, _


class GRNDetailsData(models.Model):
    _name = "grn.details.data"

    invoice_no = fields.Char(string="Invoice No")
    invoice_date = fields.Date(string="Invoice Date")
    salesperson = fields.Many2one('res.users', string="Salesperson")
    customer = fields.Many2one('res.partner', string="Customer")
    city = fields.Char(string="City")
    state = fields.Char(string="State")
    pin = fields.Char(string="Pin")
    gst_no = fields.Char(string="GST NO")
    analytic = fields.Char(string="Analytic")
    product = fields.Many2one('product.product', string="Product")
    mrp = fields.Float(string="MRP")
    article_code = fields.Char(string="Article Code")
    so_number = fields.Char(string="SO Number")
    po_number = fields.Char(string="PO Number")
    sku = fields.Char(string="SKU")
    ean = fields.Char(string="EAN")
    brand = fields.Char(string="Brand")
    uom = fields.Many2one('uom.uom', string="UOM")
    size = fields.Char(string="Size")
    color = fields.Char(string="Color")
    invoice_class = fields.Char(string="Class")  # Renamed to avoid reserved keywords
    subclass = fields.Char(string="SubClass")
    quantity = fields.Float(string="Quantity")
    grn_quantity = fields.Float(string="GRN Quantity")
    shortage = fields.Float(string="Shortage")
    transporter = fields.Char(string="Transporter")
    delivery_status = fields.Char(string="Delivery Status")
    delivery_date = fields.Date(string="Delivery Date")
    pod_status = fields.Selection([
        ('pending', 'Pending'),
        ('completed', 'Completed')
    ], string="PODs Status")
    remark = fields.Text(string="Remark")
    unit_price = fields.Float(string="Unit Price")
    discount = fields.Float(string="Discount")
    price_subtotal = fields.Float(string="Price Subtotal")
    taxes = fields.Char(string="Taxes")
    bill_net_amt = fields.Float(string="Bill Net Amt")
    price_total = fields.Float(string="Price Total")
    invoice_untaxed_amt = fields.Float(string="Invoice Untaxed Amt")
    invoice_tax_amount = fields.Float(string="Invoice Tax Amount")
    invoice_total_amt = fields.Float(string="Invoice Total Amt")
    total_sgst = fields.Float(string="Total SGST")
    total_cgst = fields.Float(string="Total CGST")
    sgst_sale_2_5_mh = fields.Float(string="SGST Sale 2.5% MH")
    cgst_sale_2_5_mh = fields.Float(string="CGST Sale 2.5% MH")
    total_igst = fields.Float(string="Total IGST")
    igst_12_output_mh = fields.Float(string="IGST 12% Output MH")
    igst_5_output_mh = fields.Float(string="IGST 5% Output MH")
    sgst_sale_6_mh = fields.Float(string="SGST Sale 6% MH")
    cgst_sale_6_mh = fields.Float(string="CGST Sale 6% MH")
    sgst_sale_9_mh = fields.Float(string="SGST Sale 9% MH")
    cgst_sale_9_mh = fields.Float(string="CGST Sale 9% MH")
    igst_18_output_mh = fields.Float(string="IGST 18% Output MH")
    igst_5_output_dl = fields.Float(string="IGST 5% Output DL")
    sgst_sale_9 = fields.Float(string="SGST Sale 9%")
    cgst_sale_9 = fields.Float(string="CGST Sale 9%")
    igst_18 = fields.Float(string="IGST 18%")
    igst_0_output_mh = fields.Float(string="IGST 0% Output MH")